# Generated by Django 3.2.13 on 2022-05-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_auto_20220522_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testapp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testapp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
