# Generated by Django 3.2.13 on 2022-05-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_auto_20220522_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='testapp',
            name='slug',
            field=models.SlugField(editable=False, max_length=60, null=True),
        ),
    ]
