# Generated by Django 3.2.13 on 2022-05-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_testapp_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testapp',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'TestApp'},
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('is_alive', models.BooleanField()),
                ('relations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test', to='Test.testapp')),
            ],
        ),
    ]
