# Generated by Django 3.2.13 on 2022-05-22 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_auto_20220522_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scor', models.IntegerField()),
                ('alive', models.BooleanField()),
                ('relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test', to='Test.testapp')),
            ],
        ),
        migrations.DeleteModel(
            name='Related',
        ),
    ]
